# Generated by Django 6.0.6 on 2026-06-11 12:58

import bio_tools.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RUNNING', 'Çalışıyor'), ('DONE', 'Tamamlandı'), ('ERROR', 'Hata')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('reads_processed', models.BigIntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quality_scores_json', models.JSONField(blank=True, null=True)),
                ('gc_histogram_data_json', models.JSONField(blank=True, null=True)),
                ('base_composition_json', models.JSONField(blank=True, null=True)),
                ('overrepresented_seqs_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FastqUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('file', models.FileField(max_length=500, upload_to=bio_tools.models.fastq_file_upload_path)),
                ('absolute_file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Yüklendi'), ('counting', 'Sayılıyor'), ('counted', 'Sayım Bitti'), ('running', 'Analiz Ediliyor'), ('done', 'Tamamlandı'), ('count_error', 'Sayım Hatası'), ('error', 'Analiz Hatası')], default='uploaded', max_length=20)),
                ('total_reads', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
