# Generated by Django 6.0.6 on 2026-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_ai_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiserviceprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
