# Generated by Django 6.0.6 on 2026-06-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Google Gemini', 'Google Gemini'), ('OpenAI', 'OpenAI'), ('Anthropic', 'Anthropic')], max_length=100, unique=True, verbose_name='Sağlayıcı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sağlayıcı',
                'verbose_name_plural': 'Sağlayıcılar',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="İsteğe bağlı isim (örn: 'Ana hesap', 'Yedek 2')", max_length=100, verbose_name='Etiket')),
                ('key', models.CharField(max_length=255, verbose_name='API Anahtarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Bu anahtarla kaç kez başarılı üretim yapıldığı', verbose_name='Kullanım Sayısı')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanım')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='ai_engine.provider', verbose_name='Sağlayıcı')),
            ],
            options={
                'verbose_name': 'API Anahtarı',
                'verbose_name_plural': 'API Anahtarları',
                'ordering': ['usage_count'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Örn: gemini-2.5-flash, gpt-4o, claude-sonnet-4', max_length=100, verbose_name='Model Adı')),
                ('label', models.CharField(blank=True, help_text="İsteğe bağlı (örn: 'Gemini 2.5 Flash')", max_length=100, verbose_name='Görünen Ad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='ai_engine.provider', verbose_name='Sağlayıcı')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modeller',
                'ordering': ['provider__service_name', 'model_name'],
                'unique_together': {('provider', 'model_name')},
            },
        ),
    ]
