"""
Django settings for ai_blog project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import locale
import os
import platform
from pathlib import Path
from dotenv import load_dotenv
import logging  # Logger için import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını yükle
dotenv_path = BASE_DIR / '.env'
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path=dotenv_path)

# DÜZELTME: Log klasörünü burada ve Path objesi ile tanımlamak daha temiz.
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

# Logger'ı erken başlatarak Redis/Cache uyarılarını yakalayabiliriz
logger = logging.getLogger(__name__)

try:
    locale.setlocale(locale.LC_TIME, 'tr_TR.UTF-8')
except locale.Error:
    try:
        locale.setlocale(locale.LC_TIME, 'tr_TR')
    except locale.Error:
        try:
            locale.setlocale(locale.LC_TIME, 'turkish')
        except locale.Error:
            print("Uyarı: Türkçe locale ayarlanamadı. Tarihler İngilizce görünebilir.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# ==============================================================================
# DÜZELTME: DEBUG AYARI
# Canlı ortamda ASLA True olmamalı. Değeri ortam değişkeninden oku.
# PythonAnywhere'de "Web" -> "Environment variables" kısmına DEBUG=False ekleyin.
# ==============================================================================
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS ayarınız DEBUG=False için doğru
ALLOWED_HOSTS = ["aiblog.pythonanywhere.com", "127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'blog.apps.BlogConfig',
    'bio_tools.apps.BioToolsConfig',

    'django_plotly_dash',
    'django_bootstrap5',
    'dash_uploader',
    'dash_apps',
    'channels',
    'channels_redis',
    'autoslug',
    'rest_framework',

    # DÜZELTME: Redis cache ve session'lar için gerekli
    'django_redis',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bio_tools.middleware.performance.PerformanceMonitoringMiddleware',
]

ROOT_URLCONF = 'ai_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_blog.wsgi.application'
ASGI_APPLICATION = "ai_blog.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES_WINDOWS = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Linux (Production) Veritabanı Ayarı (PythonAnywhere)
DATABASES_LINUX = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aiblog$default',
        'USER': 'aiblog',
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': 'aiblog.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'OPTIONS': {
            'ssl': {
                'ssl-ca': '/etc/ssl/certs/ca-certificates.crt',
            },
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}

# Platforma göre veritabanı seçimi (Bu yapı gayet iyi)
if platform.system() == 'Windows':
    DATABASES = DATABASES_WINDOWS
elif platform.system() == 'Linux':
    DATABASES = DATABASES_LINUX
else:
    DATABASES = DATABASES_WINDOWS

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"  # os.path.join yerine Path

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'  # os.path.join yerine Path

FASTQ_UPLOAD_DIR = MEDIA_ROOT / 'fastq_uploads'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Plotly Dash Ayarları
PLOTLY_DASH = {
    "ws_route": "dpd/ws/channel",
    "http_route": "dpd/views",
    "http_poke_enabled": True,
    "insert_demo_migrations": False,
    "cache_timeout_initial_arguments": 60,
    "view_decorator": None,
    "cache_arguments": True,
    "serve_locally": False,
}

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ==============================================================================
# DÜZELTME: REDIS VE CELERY AYARLARI
# Tüm 'localhost' bağlantıları kaldırıldı.
# Harici Redis URL'nizi ortam değişkeni olarak ekleyin.
# Örn: redis://:şifreniz@sunucu.com:port
# ==============================================================================
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CELERY_BROKER_URL = REDIS_URL + '/0'  # Celery için DB 0
    CELERY_RESULT_BACKEND = REDIS_URL + '/0'
else:
    logger.warning("⚠️ REDIS_URL ortam değişkeni bulunamadı. Celery çalışmayacak.")
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Istanbul'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}

NOTO_FONT_PATH = BASE_DIR / "static/fonts/NotoSans-Regular.ttf"

# ==============================================================================
# EMAIL AYARLARI
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'artificalintelligentblog@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Yükleme Limitleri
DATA_UPLOAD_MAX_MEMORY_SIZE = 5000 * 1024 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5000 * 1024 * 1024 * 1024

# ==============================================================================
# LOGGING AYARLARI
# DÜZELTME: LOG_DIR zaten yukarıda tanımlı.
# ==============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',  # Path objesi kullanımı
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'celery.log',  # Path objesi kullanımı
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
        },
        'bio_tools.performance': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
        },
    },
}

# REST Framework ayarları
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}

# ============================================================================
# CACHE CONFIGURATION - DÜZELTİLMİŞ
# DÜZELTME: Hatalı 'localhost ping' testi kaldırıldı.
# Yapılandırma doğrudan REDIS_URL değişkeninin varlığına bakıyor.
# ============================================================================

if REDIS_URL:
    logger.info("✓ REDIS_URL bulundu. Redis cache ve session'lar kullanılacak.")
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL + '/1',  # DB 1 (default cache)
            'OPTIONS': {
                'parser_class': 'redis.connection.PythonParser',
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'ai_blog',
            'TIMEOUT': 300,
        },
        'fastq_analysis': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL + '/2',  # DB 2
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'fastq',
            'TIMEOUT': 3600,
        },
        'session': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL + '/3',  # DB 3
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'session',
            'TIMEOUT': 86400,
        }
    }

    # Session'ları Redis'te sakla
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'session'

else:
    logger.warning("⚠️ REDIS_URL bulunamadı. Fallback (LocMem) cache ve DB session'lar kullanılacak.")

    # Redis yok - LocMem (RAM) cache kullan
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'default-cache',
            'TIMEOUT': 300,
            'OPTIONS': {'MAX_ENTRIES': 1000}
        },
        'fastq_analysis': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'fastq-cache',
            'TIMEOUT': 3600,
            'OPTIONS': {'MAX_ENTRIES': 500}
        },
        'session': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'session-cache',
            'TIMEOUT': 86400,
            'OPTIONS': {'MAX_ENTRIES': 2000}
        }
    }

    # Session'ları database'de sakla
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'