# Generated by Django 5.2.4 on 2025-07-12 18:17

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Google Gemini', 'Google Gemini')], max_length=100, unique=True, verbose_name='Servis Adı')),
                ('key', models.CharField(max_length=255, verbose_name='API Anahtarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Anahtarı',
                'verbose_name_plural': 'API Anahtarları',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gönderenin Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='Gönderenin E-postası')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu olarak işaretle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.TextField(verbose_name='Kullanıcı İsteği')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('tamamlandi', 'Tamamlandı'), ('hata', 'Hata')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Üretilen Başlık')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anahtar Kelimeler')),
                ('english_abstract', models.TextField(blank=True, null=True, verbose_name='İngilizce Özet (Abstract)')),
                ('turkish_abstract', models.TextField(blank=True, null=True, verbose_name='Türkçe Özet')),
                ('full_content', models.TextField(blank=True, null=True, verbose_name='Üretilen Tam İçerik')),
                ('bibliography', models.TextField(blank=True, null=True, verbose_name='Üretilen Kaynakça')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='title', unique=True)),
                ('structured_data', models.JSONField(blank=True, null=True, verbose_name='Grafik/Tablo Verileri')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Okunma Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Faydalı Oy Sayısı')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Faydasız Oy Sayısı')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Kategori')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'AI Makalesi',
                'verbose_name_plural': 'AI Makaleleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Soyad')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Bölüm/Derece')),
                ('institution', models.CharField(max_length=100, verbose_name='Okul/Kurum')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Mezuniyet Yılı')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='blog.profile')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim Bilgileri',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yetenek Adı')),
                ('level', models.PositiveIntegerField(default=80, verbose_name='Seviye (1-100)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.profile')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='İş Ünvanı')),
                ('company', models.CharField(max_length=100, verbose_name='Şirket')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='blog.profile')),
            ],
            options={
                'verbose_name': 'İş Deneyimi',
                'verbose_name_plural': 'İş Deneyimleri',
                'ordering': ['-start_date'],
            },
        ),
    ]
