# Generated by Django 5.2.4 on 2025-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedarticle',
            name='abstract',
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='english_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='İngilizce Özet (Abstract)'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='turkish_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Türkçe Özet'),
        ),
    ]
