# Generated by Django 5.2.4 on 2025-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Makale listeleme ve paylaşım için kullanılacak kapak fotoğrafı.', null=True, upload_to='article_covers/', verbose_name='Kapak Fotoğrafı'),
        ),
    ]
