# Generated by Django 6.0.6 on 2026-06-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Yalnızca yöneticiler değiştirebilir. İşaretliyse makale anasayfada görünür.', verbose_name='Anasayfada Yayında'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='yayin_talebi',
            field=models.BooleanField(default=False, help_text='Makalenizin anasayfada yayınlanması için başvurmak istiyorsanız işaretleyin.', verbose_name='Yayın için başvuruldu'),
        ),
    ]

