# Generated by Django 5.2.4 on 2025-10-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_generatedarticle_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='model_name',
            field=models.CharField(default='Google Gemini', help_text='Örn: gemini-1.5-pro, gpt-4o', max_length=100, verbose_name='Model Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='service_name',
            field=models.CharField(choices=[('Google Gemini', 'Google Gemini'), ('OpenAI', 'OpenAI'), ('Anthropic', 'Anthropic')], max_length=100, verbose_name='Servis Adı'),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('service_name', 'model_name')},
        ),
    ]
