# Generated by Django 5.2.4 on 2025-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_generatedarticle_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='structured_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Grafik/Tablo Verileri'),
        ),
    ]
