# Generated by Django 6.0.6 on 2026-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_generatedarticle_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='ai_review_notes',
            field=models.TextField(blank=True, help_text="AI'ın tespit ettiği hatalar ve düzeltme önerileri.", null=True, verbose_name='AI Düzeltme Önerileri'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='ai_review_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text="0-100 arası. AI'ın makaleyi yayına uygunluk değerlendirmesi.", null=True, verbose_name='AI Yayınlanabilirlik Skoru'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI İnceleme Tarihi'),
        ),
    ]
