# Generated by Django 6.0.6 on 2026-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_generatedarticle_reference_check_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Düzenleme Tarihi'),
        ),
    ]
